In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import talib as ta

In [12]:
path = '../dataprocessed/binance_BTC_USDT_processed.csv'
prd = pd.read_csv(path, index_col="datetime", parse_dates=True)

In [13]:
data = prd.loc[:, [col for col in prd.columns if col not in ["open", "high", "low", "close", "volume"]]]
data.head(5)

,log_time_gap,hour_sin,hour_cos,body_ratio,log_ret_1,log_ret_4,log_ret_24,volatility_4,volatility_24_ratio,dist_vwap_24,rsi_14,bb_percent_b,adx_14,mfi_14,williams_r_14
datetime,,,,,,,,,,,,,,,
2020-01-01 00:00:00,0.0,0.000000,1.000000,-0.876383,-0.002534,0.000085,-0.010255,0.002062,0.868509,-0.006511,0.364014,0.203354,0.221157,0.451141,0.182925
2020-01-01 01:00:00,0.0,0.258819,0.965926,0.733100,0.005454,0.004177,-0.006785,0.003478,1.327332,-0.000813,0.484911,0.538013,0.209931,0.455621,0.407223
2020-01-01 02:00:00,0.0,0.500000,0.866025,0.816796,0.003677,0.005867,-0.000571,0.003724,1.382640,0.002928,0.547625,0.767512,0.204227,0.503067,0.559118
2020-01-01 03:00:00,0.0,0.707107,0.707107,-0.706000,-0.002466,0.004130,-0.001574,0.004143,1.520771,0.000470,0.503330,0.630397,0.198972,0.446168,0.457169
2020-01-01 04:00:00,0.0,0.866025,0.500000,-0.516366,-0.001072,0.005593,-0.003196,0.003772,1.382208,-0.000501,0.485000,0.567066,0.191942,0.296587,0.622877

In [14]:
data.describe()

,log_time_gap,hour_sin,hour_cos,body_ratio,log_ret_1,log_ret_4,log_ret_24,volatility_4,volatility_24_ratio,dist_vwap_24,rsi_14,bb_percent_b,adx_14,mfi_14,williams_r_14
count,54736.000000,54736.000000,5.473600e+04,54736.000000,54736.000000,54736.000000,54736.000000,54736.000000,54736.000000,54736.000000,54736.000000,54736.000000,54736.000000,5.473600e+04,54736.000000
mean,0.000291,-0.000192,-3.083244e-05,0.011636,0.000041,0.000164,0.000979,0.004891,0.895114,0.000967,0.507962,0.512955,0.275296,5.028659e-01,0.527151
std,0.018736,0.707103,7.071236e-01,0.496053,0.006671,0.013044,0.031927,0.004608,0.474301,0.015673,0.121491,0.335097,0.119019,1.752036e-01,0.264178
min,0.000000,-1.000000,-1.000000e+00,-1.000000,-0.201033,-0.342863,-0.624510,0.000062,0.017288,-0.297458,0.055606,-0.563136,0.065581,-3.282749e-15,0.000000
25%,0.000000,-0.707107,-7.071068e-01,-0.408345,-0.002325,-0.004517,-0.012818,0.002145,0.536090,-0.006256,0.430562,0.262458,0.185642,3.747765e-01,0.304000
50%,0.000000,0.000000,-1.836970e-16,0.014229,0.000061,0.000173,0.000901,0.003663,0.812270,0.000696,0.507592,0.524321,0.250841,5.020322e-01,0.535023
75%,0.000000,0.707107,7.071068e-01,0.432069,0.002504,0.005035,0.015159,0.006164,1.174066,0.007954,0.584763,0.763789,0.344647,6.301740e-01,0.754976
max,1.791759,1.000000,1.000000e+00,1.000000,0.160280,0.182272,0.283191,0.151467,2.653328,0.107595,0.958543,1.575102,0.827642,1.000000e+00,1.000000